# -*- coding: utf-8 -*-
# ***************************************************************************************************
# * Copyright (C) 2025 RAM GROUP.
# *
# * This file is part of the AutoSF Project.
# *
# * AutoSF can not be copied and/or distributed without the express
# * permission of Ram Group - Tech Team.
# ***************************************************************************************************
# | --------------------------------
# | BAEDAL Automation DEV Environment Configuration
# | file: config/BAEDAL/profiles/DEV.yaml
# |
app:
  user:
    sf_loginid: "gensonpatrick.trinidad@ram.com.au.envqa"
    sf_password: "P@ssw0rd1234"
    # sf_mfa_secret: "BASE32SECRETKEY"
    refreshToken: ""
    details:
      firstname: "Genson"
      lastname: "Trinidad"
      mobileNumber: "9185793159"
      email: "gensonpatrick.trinidad@ram.com.au"