SF:
  forms:
    login:
      username:                  "css:#left > #wrap > #main > #wrapper > #content > #theloginform > #login_form > :nth-child(3) > :nth-child(2) > :nth-child(2)"
      password:                  "css:#left > #wrap > #main > #wrapper > #content > #theloginform > #login_form > :nth-child(5)"
      btnlogin:                  "css:#left > #wrap > #main > #wrapper > #content > #theloginform > #login_form > :nth-child(7)"
      login_error:               "css:#left > #wrap > #main > #wrapper > #content > #theloginform > #login_form > :nth-child(2)"
    home:
      env_qa_id:                 "css:#oneHeader > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1)"
      env_logout:                "css:#oneHeader > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(2)"














